#SELECT CUSTOMERID, SUM(AMOUNT) AS TOTAL_AMONUT
#FROM ORDER_DATA 
#GROUP BY CUSTOMERID

#SELECT * FROM CUSTOMER LIMIT 5;

#SELECT *
#FROM ORDER_DATA 
#JOIN CUSTOMER
#ON ORDER_DATA.CUSTOMERID = CUSTOMER.CUSTOMERID

SELECT CUSTOMER.CUSTOMERID, NAME, SUM(AMOUNT) AS TOTAL_AMONUT
FROM ORDER_DATA 
JOIN CUSTOMER
ON ORDER_DATA.CUSTOMERID = CUSTOMER.CUSTOMERID
GROUP BY CUSTOMER.CUSTOMERID